import numpy as np

In [ ]:
import numpy as np

In [ ]:
a1 = np.array([1,2,3,4,5,6,7])

In [ ]:
a2 = np.array([3,4,5,4,3,2,34])

In [ ]:
print(a1.ndim)

1


In [ ]:
print(a1.size)

7


In [ ]:
print(a1.dtype)

int64


In [ ]:
a3 = np.array([[1,2,3,4,5,6,7]])

In [ ]:
print(a3.ndim)

2


In [ ]:
a1 = np.array([[[1,2],[2,3]],[[3,4],[4,5]]])

In [ ]:
a6 = np.zeros(((2,2,4)))

In [ ]:
a2 = np.ones(((2,2,4)))

In [ ]:
a1

array([[[1, 2],
        [2, 3]],

       [[3, 4],
        [4, 5]]])

In [ ]:
print(a1.size)
print(a1.shape)

8
(2, 2, 2)


In [ ]:
a3= np.full(((2,3,4)),2)
a3

array([[[2, 2, 2, 2],
        [2, 2, 2, 2],
        [2, 2, 2, 2]],

       [[2, 2, 2, 2],
        [2, 2, 2, 2],
        [2, 2, 2, 2]]])

In [ ]:
s1 = np.random.random((2,3))
s1

array([[0.84148166, 0.93585016, 0.99227257],
       [0.92083494, 0.42203843, 0.1755787 ]])

In [ ]:
s2 = np.random.randint(2,4,(2,3,4))
s2

array([[[3, 3, 3, 2],
        [2, 2, 3, 2],
        [3, 2, 3, 3]],

       [[2, 3, 3, 2],
        [3, 2, 2, 3],
        [2, 3, 2, 3]]])

In [ ]:
s2=np.eye(3,3,dtype='int')
s2

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [ ]:
s1 = np.array([[[1,2,3]]])
s2 =np.array([[[1,2,3]]])

In [ ]:
np.sum([s1,s2],axis=0)


array([[[2, 4, 6]]])

In [ ]:
np.sum([s1,s2],axis=1)

array([[[1, 2, 3]],

       [[1, 2, 3]]])

In [ ]:
np.sqrt(100)

10.0

In [ ]:
a=np.arange(1,11,2)
a

array([1, 3, 5, 7, 9])

In [ ]:
a1 =np.linspace(1,10,6)
a1

array([ 1. ,  2.8,  4.6,  6.4,  8.2, 10. ])

**RETURN THE DIMENSION OF THE ARRAY**








In [ ]:
a1 =np.arange(24)
a1
a1.ndim
#reshaping the array
#only reshape the array in which the product should be the total of the array size
b = a1.reshape(6,2,2)
b.ndim

3

**Find the number of element in the array**


In [ ]:
b.size

24

In [ ]:
#FIND THE DATATYPE OF THE ARRAY
a = np.array([1,2,3,4],dtype = float)
a.dtype

dtype('float64')

In [ ]:
#NUMPY ARRAY MATHEMATICS ADDITION
import numpy as np
np.sum([20,20])

40

In [ ]:
a,b =10,20
np.sum([a,b])

30

In [ ]:
np.sum([[1,2],[3,4]],axis =0)
np.sum([[1,2],[3,4]],axis =1)
np.sum([[1,2],[3,4]])


10

In [ ]:
#NUMPY ARRAY MATHEMATICS SUBTTRACTION
np.subtract(10,20)

-10

In [ ]:
#NUMPY ARRAY MATHEMATICS (other)
np.multiply(3,4)
np.divide(2,3)

0.6666666666666666

In [ ]:
np.exp(1)
np.sqrt(9)
np.sin(30)


-0.9880316240928618

In [ ]:
#ARRAY COMPARISON
#Element wise
a=[1,2,3]
b=[2,3,4]
c=[3,4,5]
np.equal(a,b)

array([ True, False, False])

In [ ]:
#array wise comparison
a=[1,2,3,4]
b=[2,2,3,4]
c=[1,2,3,5]
np.array_equal(a,b)

False

In [ ]:
#AGRREGATE FUNCTION
a=[1,2,3,4]
np.mean(a)
#np.median(a)
#np.sum(a)
#np.max(a)
np.std(a)


1.118033988749895

In [ ]:
#CONCEPT OF BROADCASTING
a=np.array([[1,2,3,4],[1,2,3,4],[1,2,3,4]])
b=np.array([10,20,30,40])
a+b

array([[11, 22, 33, 44],
       [11, 22, 33, 44],
       [11, 22, 33, 44]])

In [ ]:
#ARRAY MANIPULATION
a=([1,2,3,4])
b=([1,4,5,7])
#concatinate two array
np.concatenate((a,b))

#Stack array row-wisw : vertically
np.vstack((a,b))
#Stack array column-wise : horizontally
#np.hstack((a,b))

array([[1, 2, 3, 4],
       [1, 4, 5, 7]])

In [6]:
#ARRAY SPLITTING
import numpy as np
a=([1,2,3,4])
b=([1,4,5,7])
np.column_stack((a,b))

array([[1, 1],
       [2, 4],
       [3, 5],
       [4, 7]])

In [17]:
import numpy as np
x =np.arange(16).reshape(4,4)
np.hsplit(x,2)
np.hsplit(x,np.array([1,2,3]))

[array([[ 0],
        [ 4],
        [ 8],
        [12]]),
 array([[ 1],
        [ 5],
        [ 9],
        [13]]),
 array([[ 2],
        [ 6],
        [10],
        [14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]])]

In [21]:
#array slicing
a = ['m','n','o','p','q',' ','r','s','t','u']
a[0:4]

['m', 'n', 'o', 'p']

In [32]:
a = np.array([[1,2,3],[26,3,4],[38,4,5]])
a[1:2,1:]
a[1:2,0:1,]

array([[26]])